// generated by pjs -- do not edit
function toStr(sexp) {
  switch (typeof(sexp)) {
    case "undefined":
      throw new Error("undefined sexp");
    case "string":
      return "\x22" + sexp + "\x22";
    case "number":
      return "" + sexp;
    case "symbol":
      return sexp.sym();
    default:
      return "(" + sexp.map(toStr).join(" ") + ")";
  }
}
exports.toStr = toStr;
