// generated by pjs -- do not edit
function isSymbol(obj, match) {
  if (!(typeof(obj) == "symbol")) {
    return false;
  }
  if (match && Symbol.keyFor(obj) != match) {
    return false;
  }
  return true;
}

function sym(name) {
  return Symbol.for(name);
}

function keyFor(sym) {
  return Symbol.keyFor(sym);
}
exports.isSymbol = isSymbol;
exports.sym = sym;
exports.keyFor = keyFor;
