// generated by pjs -- do not edit
if (a) {
  b;
} else {
  c;
}
if (a) {
  if (c) {
    if (d) {
      e;
    }
  } else {
    f;
  }
}
var a;
var a = 3 + 4;

function(x) {
  1 + x;
}

function foo(bar, baz) {
  1;
  2;
}

function foo(bar, baz) {
  return x + 1;
}
for (var i = 0; i < 4; ++i) {
  return i;
}
throw "foo";
break;
continue;
var x = new y();
new y(z);
x[1 + 2];
if (x) {
  y;
  z;
}
[1, 2, 3 + 4];
var x = {
  "foo": bar,
  x: y
};
