// generated by pjs -- do not edit
if (a) {
  b;
} else {
  c;
}
if (a) {
  if (c) {
    if (d) {
      e;
    }
  } else {
    f;
  }
}
var a;
var a = 3 + 4;

function(x) {
  1 + x;
}

function foo(bar, baz) {
  1;
  2;
}

function foo(bar, baz) {
  return x + 1;
}

function foo(bar, baz) {
  var extra = Array.prototype.slice.call(arguments, 2);
  return extra;
}
for (var i = 0; i < 4; ++i) {
  return i;
}
for (;;) {;
}
throw "foo";
break;
continue;
var x = new y(3);
new y(z);
x[1 + 2];
if (x) {
  y;
  z;
}
[1, 2, 3 + 4];
var x = {
  "foo": bar,
  x: y
};
switch (x) {
  case 0:
  case 1:
    2;
  case 3:
    4;
    break;
  default:
    5;
}
while (x) {
  y;
  z;
}
while (x) {;
}
foo.bar;
foo.bar(baz);
foo.bar(baz);
x instanceof y;
