// generated by pjs -- do not edit
if (a) {
  b;
} else {
  c;
}
if (a) {
  if (c) {
    if (d) {
      e;
    }
  } else {
    f;
  }
}
var a;
var a = 3 + 4;

function(x) {
  1 + x;
}

function foo(bar, baz) {
  1;
  2;
}

function foo(bar, baz) {
  return x + 1;
}
