// generated by pjs -- do not edit
function vars() {
  var x = 3;
  var x;
  if (1) {
    x = 2;
  } else {
    x = 3;
  }
}

function nestedIf() {
  if (1) {
    return 2;
  } else {
    return 3;
  }
}

function doubleIf() {
  if (1) {
    __pjs_0 = 2;
  } else {
    __pjs_0 = 3;
  }
  if (__pjs_0) {
    4;
  }
}

function switches() {
  switch (x()) {
    case 1:
      2;
    case 3:
      4;
  }
  var x;
  switch (y) {
    case 1:
      x = 2;
      break;
  }
  switch (z) {
    case 1:
      return 3;
  }
}
