// generated by pjs -- do not edit
function vars() {
  var x = 3;
  var x;
  if (1) {
    x = 2;
  } else {
    x = 3;
  }
}

function nestedIf() {
  if (1) {
    return 2;
  } else {
    return 3;
  }
}
