// generated by pjs -- do not edit
function toStr(sexp) {
  switch (typeof(sexp)) {
    case "undefined":
      throw new Error("undefined sexp");
    case "string":
      return "\x22" + sexp + "\x22";
    case "number":
      return "" + sexp;
    default:
      if (pjs.isSymbol(sexp)) {
        return sexp.sym();
      } else {
        return "(" + sexp.map(toStr).join(" ") + ")";
      }
  }
}
exports.toStr = toStr;
