// generated by pjs -- do not edit
function Symbol(name) {
  this.symbol = name;
}
Symbol.prototype.toString = function() {
  return "sym:" + this.symbol + "";
};
Symbol.prototype.sym = function() {
  return this.symbol;
};

function isSymbol(obj, match) {
  if (!(obj instanceof Symbol)) {
    return false;
  }
  if (match && obj.symbol != match) {
    return false;
  }
  return true;
}
var symbols = {};

function sym(name) {
  var s = symbols[name];
  if (!s) {
    s = new Symbol(name);
    symbols[name] = s;
  }
  return s;
}
exports.isSymbol = isSymbol;
exports.sym = sym;